import Head from "next/head";
import Contact from "../components/Contact";
import Header from "../components/Header";
import MainPage from "../components/MainPage";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import { Toaster } from "react-hot-toast";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster/>
      <Header />
      <MainPage />
      <Skills/>
      <Projects/>
      <Contact/>
    </div>
  );
}
